name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      # Install Google Chrome
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Remove the old ChromeDriver if it exists
      - name: Remove old ChromeDriver if exists
        run: |
          sudo rm -f /usr/local/bin/chromedriver

      # Install compatible ChromeDriver
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9]+(\.[0-9]+)+')
          echo "Installed Google Chrome version: $CHROME_VERSION"
          
          # Fetch the correct version of ChromeDriver based on the Chrome version
          DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION" || curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          
          if [[ "$DRIVER_VERSION" == *"Error"* ]] || [ -z "$DRIVER_VERSION" ]; then
            echo "Failed to retrieve a compatible ChromeDriver version, defaulting to the latest version."
            DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          fi

          echo "Using ChromeDriver version: $DRIVER_VERSION"
          
          # Download and install the correct ChromeDriver version
          wget "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
          unzip -o chromedriver_linux64.zip
          
          # Move ChromeDriver to a directory in the system's PATH and ensure it's executable
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      # Run Maven tests
      - name: Build and Test with Maven
        run: mvn -B clean package --file pom.xml
